package rblocks.transformer;

import java.util.Map;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.relauncher.FMLRelaunchLog;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin.MCVersion;

@MCVersion("1.7.2")
public class RBCore extends DummyModContainer implements IFMLLoadingPlugin
{

	protected final ModMetadata md = new ModMetadata();

	@EventHandler
	public void load(FMLInitializationEvent event)
	{
	}

	public RBCore() {
		FMLRelaunchLog.info( "[RBCore] Core Init" );
		md.autogenerated = true;
		md.credits = "AlgorithmX2";
		md.modId = getModId();
		md.version = getVersion();
		md.name = getName();
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller)
	{
		return true;
	}

	@Override
	public String[] getASMTransformerClass()
	{
		return null;
	}

	@Override
	public String getModContainerClass()
	{
		return "rblocks.transformer.RBCore";
	}

	@Override
	public String getSetupClass()
	{
		return null;
	}

	@Override
	public void injectData(Map<String, Object> data)
	{

	}

	@Override
	public String getModId()
	{
		return "RB-Core";
	}

	@Override
	public String getName()
	{
		return "RotatableBlocks Core";
	}

	@Override
	public String getVersion()
	{
		return "0.0.0.1";
	}

	@Override
	public String getDisplayVersion()
	{
		return getVersion();
	}

	public ModMetadata getMetadata()
	{
		return md;
	}

	@Override
	public String getAccessTransformerClass()
	{
		return "rblocks.transformer.RBCoreASMTransformer";
	}
}
